spring:
  profiles.active: development

---

spring:
  profiles: development

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/subway_monitor?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: password

  jwt:
    secret: "*9L@18aCZ-Mo;kjde6?<1R$IUFR%C>G-"

server:
  servlet:
    context-path: /monitor/v1
  port: 8080

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

