spring:
  profiles.active: development

---

spring:
  profiles: development

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
      showsql: true

  datasource:
    url: jdbc:mysql://localhost:3306/subway_monitor?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=FALSE&allowPublicKeyRetrieval=true
    username: root
    password: password
    initialization-mode: always

jwt:
  secret: "*9L@18aCZ-Mo;kjde6?<1R$IUFR%C>G-"

metro:
  lineStatusUrl: http://www.viaquatro.com.br

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  file: ./subway_monitor.log

